### ISSUE TITLE
blur level

### ISSUE THREAD

**Issue by halivorg** [haehnpt/blur-anything#1]
Hi Patrick!
First of all, thanks for that helpful little blur tool for browsers. I've got a proposal for a small improvement. Could you please add a setting for the blur level? Sometimes the default blur level simply is not blurry enough. If there would be a slider or a simple input field in the extension control, where the blur level could be set, it would make the tool even more useful. 
Thanks for reading
Regards!
Oliver Hahn

**Comment by haehnpt** [comment]
Hi Oliver,

thank you for the suggested changes. I have released [version 1.1](https://addons.mozilla.org/de/firefox/addon/blur_anything/) which introduces a slider in the extension settings to control the desired strength of blur.

Best,
Patrick

**Comment by halivorg** [comment]
Hi Patrick, thanks for your quick reaction and for the new version with the blur strength slider. I was quite elated, but unfortunately there is a new issue. Since the new version 1.1 the addon does not work anymore. I am using the current Firefox version 123.0.1 (64bit) under Linux OS. 
Ctrl + right click, which did the blur in the old version, now doesn't do anything at all. I even tried a private browser window with only the blur-addon active, to avoid potential addon collisions, but nothing. I could not test it under Windows systems since I have no such system around here. I am sorry about that, but do you have any idea what's going wrong here?
Thanks a lot and regards!
Oliver Hahn

**Comment by haehnpt** [comment]
Whoops, I forgot to add a default blur strength. Try either setting a value in the extension settings or updating to [patch 1.1.2](https://addons.mozilla.org/de/firefox/addon/blur_anything/).

**Comment by halivorg** [comment]
Thank you so much. Now everything works perfect! Have a nice sunday!
